--                  CONHECENDO MAIS SOBRE FUNÇÕES STRING

SELECT  NOME,
        LOWER(NOME),                     -- TODO O TEXTO EM MINUSCULO
        UPPER(NOME),                     -- TODO O TEXTO EM MAISCULO
        INITCAP(NOME),                   -- 1º LETRA EM MAISCULO PARA TODAS AS PALAVRAS DO TEXTO
        CONCAT(ESTADO,SEXO),             -- CONCATENA 2 TEXTO
        CIDADE ||'-'||ESTADO AS ENDEREÇO -- OUTRA FORMA DE CONCATENAÇÃO 
FROM TABELA_DE_CLIENTES;


SELECT  NOME_DO_PRODUTO, 
        SUBSTR(NOME_DO_PRODUTO,1,5),   -- Retorna o texto deacordo com a numeração escolha (1 até o 5)
        INSTR(NOME_DO_PRODUTO,'campo') -- Retorna a casa de inicio da palavra pesquisada na coluna
FROM TABELA_DE_PRODUTOS;

SELECT  '      MATHEUS   '        AS NOME_ESPACO,  
        LTRIM('      MATHEUS  ')  AS NOME_ESP_DIR,  -- ESPAÇOS DA ESQUERDA RETIRADOS
        RTRIM('      MATHEUS  ')  AS NOME_ESP_ESQ,  -- ESPAÇOS DA DIREITA RETIRADOS
        TRIM('      MATHEUS   ')  AS NOME_SEM_ESP   -- TODOS OS ESPAÇAÇOS RETIRADOS   
FROM DUAL;


SELECT  NOME_DO_PRODUTO,
        REPlACE(NOME_DO_PRODUTO,'Litro','L'),                  -- TROCA TODOS OS 'LITRO' POR 'L'
        REPLACE(REPLACE(NOME_DO_PRODUTO,'Litro','L'),'Ls','L') -- TROCA TODOS OS 'LITRO' E 'LS' POR 'L'
FROM TABELA_DE_PRODUTOS;

--              CONHECENDO MAIS SOBRE FUNÇÕES DE DATAS

SELECT  SYSDATE, -- DATA ATUAL
        TO_CHAR(SYSDATE,'DD/MM/YYYY HH:MM;SS') -- DATA ATUAL FORMATO DIFERENTE      
FROM DUAL;

SELECT  NOME,
        ADD_MONTHS(SYSDATE,5) AS ADD_MESES,     -- ADICIONA MESES A DATA ESCOLHIDA 
        ROUND(MONTHS_BETWEEN(SYSDATE,DATA_DE_NASCIMENTO)) AS QTD_MESES,  -- INFORMA A QTSDE MESES ENTRE AS DUAS DATAS
        TO_CHAR(DATA_DE_NASCIMENTO,'DD/MM/YYYY HH:MM:SS') AS DT_NASC,    -- FORMATO DE DATA DIFERENTE
        TO_CHAR(DATA_DE_NASCIMENTO,'DD "DE" MONTH "DE" YYYY') AS DIA_MES,-- FORMATO DE DATA DIFERENTE
        TO_CHAR(DATA_DE_NASCIMENTO,'D/MON/YYYY') AS DT_NASC,             -- FORMATO DE DATA DIFERENTE
        ROUND(SYSDATE - DATA_DE_NASCIMENTO) AS IDADE_VERDADEIRA,         -- Data atual - data de nasicimento   
        NEXT_DAY(SYSDATE,'TERÇA') AS PROXIMO_DIA,  -- PROXIMO DIA QUE SERA SEXTA FEIRA
        LAST_DAY(SYSDATE) AS ULTIMO_DIA            -- ULTIMA TERÇA DO MÊS 
FROM TABELA_DE_CLIENTES;

--              CONHECENDO MAIS SOBRE FUNÇÕES NUMERICAS

SELECT 
    3.4,
    ROUND(3.4)  AS ARRENDONDADO,
    FLOOR(3.4)  AS ARRENDONDADO_FLOOR,
    CEIL(3.4)   AS ARRENDONDA_PRA_CIMA,
    TRUNC(3.4)  AS ARRENDONDA_PRA_BAIXO,
    POWER(10,4) AS POTENCIA,
    SQRT(100)   AS RAIZ_QUADRADA,
    ABS(-10.2)  AS RETORNO_POSITIVO,
    MOD(10,6)   AS RESTO_DIVISAO,
    EXP(1)      AS EXPONENCIAL
FROM DUAL;

-- Vendedores e clientes nulos recebem 'NDA'
SELECT  
    NVL(TV.NOME,'NDA')   AS NOME_VENDEDOR,
    NVL(TV.BAIRRO,'NDA') AS BAIRRO_VENDEDOR,
    NVL(TC.NOME,'NDA')   AS NOME_CLIENTE,
    NVL(TC.BAIRRO,'NDS') AS BAIRRO_CLIENTE
FROM TABELA_DE_VENDEDORES TV
FULL JOIN TABELA_DE_CLIENTES TC
    ON TC.BAIRRO = TV.BAIRRO;
    
    
    
-- SELECIONANDO O CLIENTE E O SEU TOTAL DE GANHOS NO ANO DE 2016, ATRAVÉS DE UM TEXTO
SELECT 
    'O CLIENTE '||INITCAP(C.NOME) ||' FATUROU '||
    TO_CHAR(ROUND(SUM(IT.QUANTIDADE*PRECO),2))||' NO ANO DE ' ||
    TO_CHAR(NF.DATA_VENDA,'YYYY') AS RESULTADO
FROM TABELA_DE_CLIENTES C
FULL JOIN NOTAS_FISCAIS NF
    ON C.CPF = NF.CPF
FULL JOIN ITENS_NOTAS_FISCAIS IT
    ON NF.NUMERO = IT.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA,'YYYY') = '2016'
GROUP BY C.NOME,TO_CHAR(NF.DATA_VENDA,'YYYY')
ORDER BY C.NOME;