
-- CONSULTAS COM SUBQUERYS PADRÃO
SELECT * 
FROM TABELA_DE_CLIENTES
WHERE BAIRRO IN (SELECT DISTINCT BAIRRO 
                 FROM TABELA_DE_VENDEDORES);
                 
                 


-- CRIANCDO UM VIEW SOMA_EMBALAGENS
CREATE VIEW VW_SOMA_EMBALAGENS AS 
SELECT
        SOMA_EMBALAGEM.EMBALAGEM,
        SOMA_EMBALAGEM.SOMA_PRECO
FROM (SELECT  EMBALAGEM,
      SUM(PRECO_DE_LISTA) AS SOMA_PRECO
      FROM TABELA_DE_PRODUTOS 
      GROUP BY EMBALAGEM
      ) SOMA_EMBALAGEM;


-- Uma consulta com um meio alternativo para não usar o HAVING 
SELECT  JB.nome_do_produto,
        JB.codigo_do_produto,
        JB.sum_qtd
FROM( SELECT    INF.CODIGO_DO_PRODUTO,
                TP.NOME_DO_PRODUTO,
                SUM(INF.QUANTIDADE) AS SUM_QTD
    FROM ITENS_NOTAS_FISCAIS INF
    INNER JOIN TABELA_DE_PRODUTOS TP 
    ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
    GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO ) JB
WHERE JB.sum_qtd > 1000
ORDER BY JB.sum_qtd DESC;