-- CRIAÇÃO DAS TABELAS
CREATE TABLE PRODUTO_EXERCICIO(
    COD VARCHAR(5) NOT NULL,
    DESCRICAO VARCHAR(100),
    CATEGORIA VARCHAR(100)
);

CREATE TABLE PRODUTO_VENDA_EXERCICIO(
    ID_VENDA NUMBER(5) NOT NULL,
    COD_PRODUTO VARCHAR(5),
    DATA DATE NULL,
    QUANTIDADE FLOAT,
    PRECO FLOAT,
    VALOR_TOTAL FLOAT,
    PERCENTUAL_IMPOSTO FLOAT
);

ALTER TABLE PRODUTO_VENDA_EXERCICIO
RENAME COLUMN ID_VENDA
TO ID;


--      CHAVES PRIMARIAS
ALTER TABLE PRODUTO_EXERCICIO ADD CONSTRAINT PK_COD_PRODUTO_EXERCICIO
PRIMARY KEY(COD);

ALTER TABLE PRODUTO_VENDA_EXERCICIO ADD CONSTRAINT PK_ID_VENDA_PRODUTO_VENDA_EXERCICIO
PRIMARY KEY (ID_VENDA);

--      CHAVE ESTRANGEIRA
ALTER TABLE PRODUTO_VENDA_EXERCICIO ADD CONSTRAINT FK_PRODUTO_EXERCICIO_PRODUTO_VENDA_EXERCICIO
FOREIGN KEY (COD_PRODUTO)
REFERENCES PRODUTO_EXERCICIO (COD);
