--ATUALIZAÇÃO DAS INFORMAÇÕES DOS VENDEDORES

UPDATE TB_PRODUTOS
SET EMBALAGEM = 'LATA'
WHERE PRODUTO = '1037797';

--
UPDATE TB_PRODUTOS
SET nome = 'Clean - 350 ml - Laranja', Tamanho = '350',PRECO_LISTA = 5.50
WHERE PRODUTO = '1037797';

--
UPDATE TB_VENDEDORES
SET PERCENTUAL_COMISSAO = 0.18
WHERE MATRICULA IN('OO233','00400','00810','00414');

--
UPDATE TB_VENDEDORES
SET PERCENTUAL_COMISSAO = 0.20
WHERE MATRICULA = '00934';


-- EXCLUSÃO DOS REGISTROS
DELETE FROM TB_PRODUTOS
WHERE PRODUTO = '1037797';

--
DELETE FROM TB_VENDEDORES
WHERE MATRICULA = '00400';


-- ALTERAÇÕES DA TABELA
ALTER TABLE TB_PRODUTOS ADD CONSTRAINT PK_TB_PRODUTOS
PRIMARY KEY (PRODUTO);

--
ALTER TABLE TB_VENDEDORES ADD CONSTRAINT PK_TB_VENDEDORES
PRIMARY KEY(MATRICULA);

--
ALTER TABLE TB_CLIENTES ADD CONSTRAINT PK_TB_CLIENTES
PRIMARY KEY (CPF);
