-- Criação da tabela TB_CLIENTES
CREATE TABLE TB_CLIENTES(
    CPF VARCHAR(11),
    NOME VARCHAR(100),
    ENDERECO1 VARCHAR(150),
    ENDERECO2 VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO CHAR(2),
    CEP VARCHAR(8),
    DT_NASCIMENTO DATE,
    IDADE INTEGER,
    SEXO CHAR(1),
    LIMITE_CREDITO NUMBER(15,2),
    VOLUME_COMPRA NUMBER,
    PRIMEIRA_COMPRA NUMBER(1)
);

DROP TABLE TB_CLIENTES;

-- CRIAÇÃO DA TABELA TB_VENDEREDORES
CREATE TABLE TB_VENDEDORES(
    MATRICULA VARCHAR(20),
    NOME VARCHAR(100),
    DATA_ADMISSAO DATE,
    PERCENTUAL_COMISSAO NUMBER(4,2)
);
