-- DANDO PRIVILEGIO E UM SINONIMO PARA A PKG_PRODUTO_EXERCICIO
GRANT EXECUTE ON PKG_PRODUTO_EXERCICIO TO USER_APP;
GRANT EXECUTE ON PKG_CLIENTE TO USER_APP;
CREATE PUBLIC SYNONYM PKG_PROD_EXERCICIO FOR USER_DEV.PKG_PRODUTO_EXERCICIO;
CREATE PUBLIC SYNONYM PKG_CLIENTE FOR USER_DEV.PKG_CLIENTE;



-- EXECU��ES PARA AN�LISE DE ROTINAS PACKAGES DE PKG_CLIENTE
EXECUTE DEPTREE_FILL('TABLE','USER_DEV','CLIENTE');
EXECUTE DEPTREE_FILL('PROCEDURE','USER_DEV','INCLUIR_CLIENTE');
EXECUTE DEPTREE_FILL('PROCEDURE','USER_DEV','EXCLUIR_CLIENTE');
EXECUTE DEPTREE_FILL('PROCEDURE','USER_DEV','ATUALIZAR_CLI_SEG_MERCADO');
EXECUTE DEPTREE_FILL('PROCEDURE','USER_DEV','ATUALIZAR_FATURAMENTO_PREVISTO');

EXECUTE DEPTREE_FILL('FUNCTION','USER_DEV','OBTER_CATEGORIA_CLIENTE');
EXECUTE DEPTREE_FILL('FUNCTION','USER_DEV','FORMAT_CNPJ');
EXECUTE DEPTREE_FILL('FUNCTION','USER_DEV','VERIFICA_SEGMENTO_MERCADO');

-- REGISTROS QUE ESTÃO LIGADOS A EXECUÇÃO DA PROCEDURE DEPTREE_FILL
SELECT * FROM deptree ORDER BY SEQ# ;

-- DELETE DE ROTINAS EXTERNAS DE PCKAGES DE PKG CLIENTE
DROP PROCEDURE INCLUIR_CLIENTE;
DROP PROCEDURE EXCLUIR_CLIENTE;
DROP PROCEDURE ATUALIZAR_CLI_SEG_MERCADO;
DROP PROCEDURE ATUALIZAR_FATURAMENTO_PREVISTO;
DROP PROCEDURE FORMAT_CNPJ;

DROP FUNCTION OBTER_CATEGORIA_CLIENTE;
DROP FUNCTION VERIFICA_SEGMENTO_MERCADO;


-- EXECU��ES PARA AN�LISE DE ROTINAS PACKAGES DE PKG_CLIENTE
EXECUTE DEPTREE_FILL('PROCEDURE','USER_DEV','INCLUINDO_DADOS_VENDA');
EXECUTE DEPTREE_FILL('PROCEDURE','USER_DEV','INCLUINDO_PRODUTO');
EXECUTE DEPTREE_FILL('FUNCTION','USER_DEV','RETORNA_CATEGORIA');
EXECUTE DEPTREE_FILL('FUNCTION','USER_DEV','RETORNA_IMPOSTO');

-- REGISTROS QUE ESTÃO LIGADOS A EXECUÇÃO DA PROCEDURE DEPTREE_FILL
SELECT * FROM deptree ORDER BY SEQ# ;

-- DELETE DE ROTINAS EXTERNAS DE PCKAGES DE PKG CLIENTE
DROP PROCEDURE INCLUINDO_DADOS_VENDA;
DROP PROCEDURE INCLUINDO_PRODUTO;

DROP FUNCTION RETORNA_CATEGORIA;
DROP FUNCTION RETORNA_IMPOSTO;

-- EXECU��ES DE ROTINAS EXTERNAS DE PCKAGES DE PKG_PRODUTO_EXERCICIO