-- ATUALIZAMOS TODOS OS REGISTROS COM O LOOP PARA MELHOR APROVEITAMENTO DE CODIGO E  LEITURA
-- LOOP É PARECIDO COM O WHILE DO PYTHON, MAS CONDIÇÃO E COLOCADA NO FINAL EM EXIT WHEN.

DECLARE
    vSEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE:= 1;
    vID CLIENTE.ID%TYPE := 1;
    vTOTAL_CLIENTE INTEGER;
BEGIN
    SELECT COUNT(*) INTO vTOTAL_CLIENTE FROM CLIENTE;
    LOOP
        ATUALIZAR_SEGMERCADO(vID,vSEGMERCADO_ID);
        vID := vID+1;
    EXIT WHEN vID > vTOTAL_CLIENTE;
    END LOOP;
END;

SELECT * FROM CLIENTE;
--------------------------------------------------------------------------------------------------------------------------------
-- ATUALIZAMOS TODOS OS REGISTROS COM O LOOP 'FOR' PARA MELHOR APROVEITAMENTO DE CODIGO E LEITURA DO LOOP ANTERIOR
--  O LOOP 'FOR' É PARECIDO COM O FOR DO PYTHON, MAS É OBRIGATÓRIO O 'END LOOP' AO FINAL..
DECLARE
    vSEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE:= 1;
    vTOTAL_CLIENTE INTEGER;
BEGIN
    SELECT COUNT(*) INTO vTOTAL_CLIENTE FROM CLIENTE; 
    FOR vID in vTOTAL_CLIENTE;
        ATUALIZAR_SEGMERCADO(vID,vSEGMERCADO_ID);
    END LOOP;
END;
