 -- ULTILIZANDO O CURSOR ATRAVÉS DE UM WHILE PARA ALTERA TODOS OS SEGMERCADO_ID 
DECLARE
    vSEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE := 2;
    vID CLIENTE.ID%TYPE;
    CURSOR CUR_CLIENTE IS SELECT ID FROM CLIENTE;
BEGIN
    OPEN CUR_CLIENTE;
    FETCH CUR_CLIENTE INTO vID;
    WHILE CUR_CLIENTE%FOUND LOOP
        ATUALIZAR_SEGMERCADO(vID,vSEGMERCADO);
        FETCH CUR_CLIENTE INTO vID;
    END LOOP;
    CLOSE CUR_CLIENTE;
END;


-- REAZILAND A MESMA ALTERÇÃO ACIMA, MAS, COM UM TEXTO MAIS LEGIVEL COM O LOOPING FOR
DECLARE
    vSEGMERCADO CLIENTE.SEGMERCADO_ID%TYPE :=3;
    CURSOR CUR_CLIENTE IS SELECT ID FROM CLIENTE;
BEGIN
    FOR LINHA IN CUR_CLIENTE LOOP
        ATUALIZAR_SEGMERCADO(LINHA.ID,vSEGMERCADO);
    END LOOP;
END;


SELECT * FROM CLIENTE;