USE VENDAS_SUCOS;

UPDATE VENDAS_SUCOS.PRODUTOS
	SET PRECO_lISTA = 5,
		EMBALAGEM = 'PET' ,
		TAMANHO = '1 LITRO',
        DESCRITOR = 'SABOR DA Montanha -1litro-Uva'
 WHERE CODIGO = '1000889';


UPDATE VENDAS_SUCOS.PRODUTOS
	SET PRECO_LISTA = PRECO_LISTA * 1.1
   WHERE SABOR = 'Maracujá';   
COMMIT;

UPDATE VENDAS_SUCOS.CLIENTE
	SET ENDERECO = 'R. Jorge Emilio 23',
		BAIRRO   = 'Santo Amaro',
        CIDADE   = 'São Paulo',
        CEP      = '8833223'
WHERE CPF = '19290992743';
COMMIT;