USE VENDAS_SUCOS;

DELIMITER $$
CREATE FUNCTION `FUNC_VALOR_ALEATORIO`(vmin int, vmax int) RETURNS int
BEGIN
	declare vretorno int;
	select floor(rand() * (vmax - vmin+1) +vmin) 
			into vretorno;
    
RETURN vretorno;
END;
DELIMITER ;
------------------------------------------------------------------------------------------------------------------

DELIMITER $$
CREATE FUNCTION FUNC_RETORNA_CLIENTE()
 RETURNS VARCHAR(11)
BEGIN
	DECLARE VRETORNO VARCHAR(11);
    DECLARE NUM_MAX_CLIENTE INT;
    DECLARE NUM_ALEATORIO INT; 
    
    SELECT COUNT(*) 
    INTO NUM_MAX_CLIENTE 
		FROM VENDAS_SUCOS.CLIENTE;
	
    SET NUM_ALEATORIO = FUNC_VALOR_ALEATORIO(1, NUM_MAX_CLIENTE);
	SET NUM_ALEATORIO = NUM_ALEATORIO -1;
    SELECT CPF
    INTO VRETORNO 
		FROM VENDAS_SUCOS.CLIENTE 
	  LIMIT NUM_ALEATORIO,1;
    
RETURN VRETORNO;
END;
DELIMITER;
SELECT FUNC_RETORNA_CLIENTE();

------------------------------------------------------------------------------------------------------------------

DELIMITER $$
CREATE FUNCTION FUNC_RETORNA_VENDEDOR()
 RETURNS VARCHAR(5)
BEGIN
	DECLARE VRETORNO_MATRICULA VARCHAR(5);
    DECLARE NUM_MAX_VENDEDOR INT;
    DECLARE NUM_ALEATORIO INT; 
    
    SELECT COUNT(*) 
    INTO NUM_MAX_VENDEDOR
		FROM VENDAS_SUCOS.VENDEDORES;
	
    SET NUM_ALEATORIO = FUNC_VALOR_ALEATORIO(1,NUM_MAX_VENDEDOR);
	SET NUM_ALEATORIO = NUM_ALEATORIO -1;
    SELECT MATRICULA
    INTO VRETORNO_MATRICULA
		FROM VENDAS_SUCOS.VENDEDORES 
	  LIMIT NUM_ALEATORIO,1;
    
RETURN VRETORNO_MATRICULA;
END;
DELIMITER;
/


SELECT FUNC_RETORNA_VENDEDOR();
SELECT * FROM VENDEDORES;

------------------------------------------------------------------------------------------------------------------
DELIMITER $$
CREATE FUNCTION FUNC_RETORNA_PRODUTO()
 RETURNS VARCHAR(10)
BEGIN
	DECLARE VRETORNO_PRODUTO VARCHAR(10);
    DECLARE NUM_MAX_PRODUTO INT;
    DECLARE NUM_ALEATORIO INT; 
    
    SELECT COUNT(*) 
    INTO NUM_MAX_PRODUTO
		FROM VENDAS_SUCOS.PRODUTOS;
	
    SET NUM_ALEATORIO = FUNC_VALOR_ALEATORIO(1,NUM_MAX_PRODUTO);
	SET NUM_ALEATORIO = NUM_ALEATORIO -1;
    SELECT CODIGO
    INTO VRETORNO_PRODUTO
		FROM VENDAS_SUCOS.PRODUTOS
	  LIMIT NUM_ALEATORIO,1;
    
RETURN VRETORNO_PRODUTO;
END;
DELIMITER;
/

SELECT FUNC_RETORNA_PRODUTO();

------------------------------------------------------------------------------------------------------------------

DELIMITER $$
CREATE PROCEDURE SP_INSERIR_VENDA(VDATA DATE, VMAX_ITENS INT, VMAX_QTD INT)
BEGIN
	DECLARE NUM_ITENS_NOTAS INT;
	DECLARE VCLIENTE VARCHAR(11);
	DECLARE VCODIGO_PRODUTO VARCHAR(10); 
	DECLARE VMATRICULA_VENDEDOR VARCHAR(5);
    DECLARE VPRECO FLOAT;
    DECLARE VITENS INT;
    DECLARE VNUM_NOTAS INT;
    DECLARE VCONTADOR INT DEFAULT 1;
    DECLARE VQUANTIDADE INT;
    
    SELECT MAX(NUMERO+1) 
    INTO VNUM_NOTAS
		FROM VENDAS_SUCOS.NOTAS;
        
    SET VMATRICULA_VENDEDOR = VENDAS_SUCOS.FUNC_RETORNA_VENDEDOR();
    SET VCLIENTE	 	    = VENDAS_SUCOS.FUNC_RETORNA_CLIENTE();
    SET VITENS				= VENDAS_SUCOS.FUNC_VALOR_ALEATORIO(1, VMAX_ITENS);
    
    INSERT INTO VENDAS_SUCOS.NOTAS(NUMERO, DATA, CPF, MATRICULA, IMPOSTO)
		VALUES (VNUM_NOTAS,VDATA,VCLIENTE,VMATRICULA_VENDEDOR,0.18);
        
	WHILE VCONTADOR <= VITENS 
	DO
		SET VCODIGO_PRODUTO	= VENDAS_SUCOS.FUNC_RETORNA_PRODUTO();
		SET VQUANTIDADE = FUNC_VALOR_ALEATORIO(10,VMAX_QTD);
        
        SELECT COUNT(*) INTO NUM_ITENS_NOTAS
			FROM VENDAS_SUCOS.ITENS_NOTAS
		   WHERE NUMERO = VNUM_NOTAS
			AND CODIGO = VCODIGO_PRODUTO;
           
			IF NUM_ITENS_NOTAS = 0 THEN 
				SELECT PRECO_LISTA INTO VPRECO
					FROM VENDAS_SUCOS.PRODUTOS
				   WHERE CODIGO = VCODIGO_PRODUTO;
		
				INSERT INTO VENDAS_SUCOS.ITENS_NOTAS(NUMERO, CODIGO, QUANTIDADE, PRECO)
					VALUES (VNUM_NOTAS, VCODIGO_PRODUTO, VQUANTIDADE, VPRECO);
			END IF;	
    
		SET VCONTADOR = VCONTADOR + 1;
	END WHILE;
END
DELIMITER ;



CALL SP_INSERIR_VENDA('20190517',3,100);